apiVersion: apps/v1
kind: Deployment
metadata:
  name: fyle-deployment
  labels:
    app: fyle
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fyle
  template:
    metadata:
      labels:
        app: fyle
    spec:
      containers:
      - name: python-container
        image: skc3766/fyle
        ports:
        - containerPort: 80
